In [18]:
%pylab inline

Populating the interactive namespace from numpy and matplotlib


`%matplotlib` prevents importing * from pylab and numpy


In [3]:
import cPickle as pickle

In [1]:
import gefry2

In [4]:
with open('./spec.pkl') as f:
    P, obs, sigma = pickle.load(f)

In [7]:
# Location of the source (meters)
print(P.source.loc)

[158  98]


In [10]:
# Intensity
print("{:.4E}".format(P.source.intensity))

3.2140E+09


In [19]:
# Cross sections
savetxt("cross_sections.dat", P.domain.sigmas)
        
print(P.domain.sigmas)

[ 0.05720516  0.05776049  0.04943674  0.04552821  0.05332512  0.04855489
  0.05652938  0.05807132  0.05368017  0.05863512  0.05708592  0.05356378
  0.05719273  0.05036514  0.04235439  0.04389705  0.04255509  0.04809024
  0.05839909  0.05208743  0.04124017  0.05148868  0.04206888  0.05734774
  0.05802029  0.0437273   0.05533729  0.05706262  0.05278673  0.05696951
  0.04786608  0.0490115   0.04866986  0.05212126  0.05271452  0.04765085
  0.04191435  0.05852653  0.04661406  0.05093589  0.05008964  0.04431365
  0.04666549  0.05744369  0.04850174  0.0448708   0.04509586  0.04381561
  0.05104843  0.05459858  0.05683899  0.04905003  0.04601799  0.04520532
  0.05787082  0.04880625  0.04596143  0.04372173  0.04342586  0.05116707
  0.0534282   0.05115871  0.04888709  0.04827456  0.04530798  0.04514278
  0.04333619  0.04141195  0.05039457  0.05944784]


In [25]:
# Detector locations
dXY = array([i.loc for i in P.detectors])
savetxt("detector_locs.dat", dXY)

print(dXY)

[[  68.7401029    35.76719126]
 [  66.40829599  119.5157862 ]
 [   4.09288418   48.11233654]
 [ 190.20050205   50.16141249]
 [  93.95789422   99.89302781]
 [ 189.25480223   19.21886672]
 [ 154.48877076    2.9933617 ]
 [ 188.90616948  141.27786291]
 [ 119.90370763  160.0061866 ]
 [ 214.49842459   77.97497978]]


In [26]:
dir(P.detectors[0])

['A',
 '__class__',
 '__delattr__',
 '__dict__',
 '__doc__',
 '__format__',
 '__getattribute__',
 '__hash__',
 '__init__',
 '__module__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'dwell',
 'epsilon',
 'loc']

In [29]:
# Detector face areas
print(array([i.A for i in P.detectors]))

[ 0.005806  0.005806  0.005806  0.005806  0.005806  0.005806  0.005806
  0.005806  0.005806  0.005806]


In [30]:
# Dwell times
print(array([i.dwell for i in P.detectors]))

[ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]


In [31]:
# Efficiencies
print(array([i.epsilon for i in P.detectors]))

[ 0.62  0.62  0.62  0.62  0.62  0.62  0.62  0.62  0.62  0.62]


In [33]:
# Observations
savetxt("observations.dat", obs)

print(obs)

[[378 483 320 629 484 352 405 658 628 519]
 [369 470 313 620 495 349 404 685 650 511]
 [332 431 285 566 470 315 370 621 604 502]
 [356 451 298 591 478 335 370 669 638 515]
 [378 503 325 639 506 353 409 701 648 534]
 [361 460 293 607 482 326 365 643 599 493]
 [373 470 307 605 465 326 387 647 636 535]
 [351 472 302 606 491 346 373 636 605 495]
 [383 482 317 631 475 351 399 640 613 543]
 [350 426 292 579 458 318 377 639 582 495]]


In [37]:
# Uncertainties
savetxt("uncertainties.dat", sigma)
print(sigma)

[[ 19.4422221   21.97726098  17.88854382  25.07987241  22.          18.76166304
   20.1246118   25.65151068  25.05992817  22.7815715 ]
 [ 19.20937271  21.67948339  17.69180601  24.8997992   22.24859546
   18.68154169  20.09975124  26.17250466  25.49509757  22.60530911]
 [ 18.22086716  20.76053949  16.88194302  23.79075451  21.67948339
   17.74823935  19.23538406  24.91987159  24.57641145  22.4053565 ]
 [ 18.86796226  21.23676058  17.2626765   24.31049156  21.86321111
   18.30300522  19.23538406  25.86503431  25.25866188  22.69361144]
 [ 19.4422221   22.42766149  18.02775638  25.27844932  22.49444376
   18.78829423  20.22374842  26.47640459  25.45584412  23.10844002]
 [ 19.          21.44761059  17.11724277  24.63736999  21.9544984
   18.05547009  19.10497317  25.35744467  24.4744765   22.20360331]
 [ 19.31320792  21.67948339  17.52141547  24.59674775  21.56385865
   18.05547009  19.67231557  25.43619468  25.21904043  23.13006701]
 [ 18.734994    21.72556098  17.3781472   24.61706725  2